App/App/urls.py
from django.contrib import admin
from django.urls import include, path
from Books import views

urlpatterns = [
    path("", views.book_search, name="landing_page"),
    path('login/', include('Login.urls')),
    path('book/', include('Books.urls')),
    path('admin/', admin.site.urls),
]

App/Books/urls.py
from django.urls import path

from Books import views

app_name = "Books"
urlpatterns = [
    path('', views.book_search, name='book_search'),
    path('datail', views.detail, name='detail'),
    path('thoughts/<str:title>/<str:authors>/<path:thumbnail>', views.thoughts, name='thoughts'),
    path('thoughts/<str:title>/<str:authors>/', views.thoughts, name='thoughts'),
    path('thoughts/<str:title>', views.thoughts, name='thoughts'),
    path('thoughts/', views.thoughts, name='thoughts'),
    path('readend', views.readend, name='readend'),
    path('deletenotread', views.delete_not_read, name='delete_not_read'),
    
]

App/Books/models.py
from django.db import models
from django import utils

# Create your models here.
class M_Genre(models.Model):
    """
    お気に入り登録できるジャンルの情報を保持するモデル
    """
    id=models.AutoField(primary_key=True)
    name = models.TextField(null=False, blank=False,unique=True)
    insertdate = models.DateField(default=utils.timezone.now)
    updatedate = models.DateField(default=utils.timezone.now)
    deleteflag = models.BooleanField(default=False)

class T_Record(models.Model):
    """
    本の感想を登録しておくモデル。
    """
    username = models.TextField(null=False, blank=False)
    title = models.TextField(null=False, blank=False)
    readdate = models.DateField(null=False, blank=False, default=utils.timezone.now)
    thoughts = models.TextField(null=False, blank=True, default="")
    readflag = models.BooleanField(default=True)
    insertdate = models.DateField(default=utils.timezone.now)
    updatedate = models.DateField(default=utils.timezone.now)
    deleteflag = models.BooleanField(default=False)

    class Meta:
        constraints = [
           # 複合キーが駄目っぽいので、でユニーク制約でそれっぽくする
           models.UniqueConstraint(fields=['username', 'title'], name='unique_T_Record')
       ]

App/Books/views.py
import inspect
from typing import Counter
from django import utils
from django.http.response import HttpResponseBadRequest, JsonResponse
from django.shortcuts import render
from Books.models import T_Record
from Login.models import M_User
from utils.api_search import search_from_params, GoogleBooksStrs
from utils.make_display_data import make_user_config_data
from utils.need_login import need_login

# Create your views here.
class SearchCounter:
    """[summary]
    本を検索した時に、startIndex > allItems になってエラーを出さないようにするためのクラス
    """
    allitems:int
    def __init__(self):
        self.allitems = 200

    def change_counter(self, allitem:int):
        """[summary]
            allItemsの値を更新する(小さい時だけ更新)
        Args:
            allitem (int): GoogleBooksApiの検索結果の数
        """
        if self.allitems < allitem:
            self.allitems = allitem
        return
    
    def canSearch(self, startIndex:int)->bool:
        """[summary]

        Args:
            startIndex (int): クエリに含めるstartIndexの値

        Returns:
            bool: startIndex < totalItems ならTrue
        """
        return startIndex < self.allitems
    
counter = SearchCounter()

def book_search(request):
    """
    Booksのindex page 
    Post なら検索結果をJspnで返す
    Getなら検索ページを表示する
    """
    if request.method=="POST":
        try:
            author = request.POST.get("author","")
            title = request.POST.get("title","")
            startindex = 40 * int(request.POST.get("next_int","0"))

            # 検索を続けた時に、 startIndex > totalItems となるとエラーになるので回避する処理    
            if startindex == 0:
                datas = search_from_params(auth=author, title=title, startindex=startindex)
            elif counter.canSearch(startindex):
                datas = search_from_params(auth=author, title=title, startindex=startindex)
            else:
                datas = list({})
            
            result = {"datas":datas}
            if len(datas) == 0:
                response = JsonResponse({"error": "検索結果が0件です"})
                response.status_code = 500
                return response
            
            # totalItems の数を更新する
            counter.change_counter(int(datas[0][GoogleBooksStrs.totalitems]))
            return JsonResponse(result)
        except Exception as e:
            print(f"{inspect.currentframe().f_back.f_code.co_filename},{inspect.currentframe().f_back.f_lineno},{e}")
            response = JsonResponse({"error": "検索時エラーが起きました。再度検索してみてください。"})
            response.status_code = 500
            return response
        
    return render(request, "book_search.html")


def detail(request):
    """
    本の詳細ページ
    """
    if request.method =="POST":
        result = {}
        for k in GoogleBooksStrs.result_keys:
            if k == GoogleBooksStrs.authors:
                try:
                    author = request.POST[k]
                except Exception as e:
                    print(f"{inspect.currentframe().f_back.f_lineno},{e}")
                    author = "noinfo"
                result[k] = author
            elif k == GoogleBooksStrs.imageLinks:
                try:
                    thumbnail = eval(request.POST[k])
                except Exception as e:
                    print(f"{inspect.__name__},{inspect.currentframe().f_back.f_lineno},{e}")
                    thumbnail = {'thumbnail':"/static/noimage.png"}
                result[k] = thumbnail
            elif k in request.POST.keys():
                result[k]=request.POST[k]
        search_result = search_from_params(auth=author)
        data ={"data":result, "search_result": search_result}
        return render(request, "detail.html", data)
    
    return render(request, "book_search.html")


@need_login(redirect_field_name="index.html", err_msg="登録にはサインアップ、ログインが必要です。")
def thoughts(request, title="", authors="", thumbnail=""):
    """[summary]
    感想登録
    """
    if request.method == "POST":
        username = str(request.user)
        title = request.POST.get("title","")
        readdate = request.POST.get("readdate", utils.timezone.now())
        thoughts = request.POST.get("thoughts","")
        readflag = eval(request.POST.get("readflag","True"))
        try:
            record, is_created = T_Record.objects.get_or_create(username=username, title= title)
            record.readdate = readdate
            record.thoughts = thoughts
            record.readflag = readflag
            record.save()
            data = make_user_config_data(username)
            return render(request, "config.html",data)
        except Exception as e:
            print(f"{inspect.currentframe().f_back.f_code.co_filename},{inspect.currentframe().f_back.f_lineno},{e}")
            data = {"title": title, "msg":"保存に失敗しました"}
            return render(request, "config.html",data)
        
    data = {"title":title, "authors":authors, "thumbnail":thumbnail}
    return render(request, "detail.html", data)

def readend(request):
    """
    読みたい本を既読本にする。
    """
    username = request.user
    if request.method == "POST":
        title = request.POST.get("title","")
        print(f"title={title}, uer={username}")
        try:
            record = T_Record.objects.get(username=username, title=title)
            record.readflag = True
            record.readdate = utils.timezone.now()
            record.save()
            data = make_user_config_data(username)
            
        except Exception as e:
            print(f"{inspect.currentframe().f_back.f_code.co_filename},{inspect.currentframe().f_back.f_lineno},{e}")
            data = make_user_config_data(username)
            data["msg"] = "更新に失敗しました"
            
        return render(request, "config.html",data)
    else:
        data = make_user_config_data(username)
        return render(request, "config.html",data)

def delete_not_read(request):
    """
    読みたい本を削除する
    """
    username = request.user
    if request.method == "POST":
        title = request.POST.get("title","")
        print(f"title={title}, uer={username}")
        try:
            record = T_Record.objects.get(username=username, title=title)
            record.delete()
            data = make_user_config_data(username)
            
        except Exception as e:
            print(f"{inspect.currentframe().f_back.f_code.co_filename},{inspect.currentframe().f_back.f_lineno},{e}")
            data = make_user_config_data(username)
            data["msg"] = "削除に失敗しました"
            
        return render(request, "config.html",data)
    else:
        data = make_user_config_data(username)
        return render(request, "config.html",data)

App/Books/templates/book_search.html
{% extends 'base.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/Login/base.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/Books/book_search.css' %}">
{% endblock %}

{% block contents %}

<div class="container-fluid content">
    <!-- 検索フォーム -->
    <div class="card card-container mb-auto" id="searchform">
        <h5 class="card-header">検索</h5>
        <div class="card-body">
            <form action="#" class="text-center form-signin">
                <div class="form-group row">
                    <label for="author" class="col-sm-2 col-form-label ">
                        <h5>著者</h5>
                    </label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="author" name="auth">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="title" class="col-sm-2 col-form-label">
                        <h5>
                            タイトル
                        </h5>
                    </label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="title" placeholder="" name="title">
                    </div>
                </div>
                <button class="btn btn-lg btn-primary btn-block btn-signin searcbutton" id="top_searchbutton"
                    type="button">検索</button>
                <p class="err_msg"></p>
        </div>
        </form>
    </div>
</div>

<!-- 検索結果 -->
<div class="container-lg mb-5">
    <!-- <h3>検索結果</h3> -->
    <div class="row row-cols-1 row-cols-md-1 row-cols-lg-2 row-cols-xl-3 g-4" id="searchresult">
        {% for data in datas %}
        <div class="col">
            <form action="{% url 'Books:detail'%}" method="post">
                {% csrf_token %}
                <input type="hidden" value="{{data.title}}" name="title">
                <input type="hidden" value="{{data.imageLinks}}" name="imageLinks">
                <input type="hidden" value="{{data.description}}" name="description">
                <input type="hidden" value="{{data.authors}}" name="authors">
                <input type="hidden" value="{{data.publishedDate}}" name="publishedDate">
                <input type="hidden" value="{{data.pageCount}}" name="pageCount">

                <div class="card mb-3">
                    <div class="row g-0">
                        <div class="col-sm-4">
                            <button type="submit">
                                <img src="{{data.imageLinks.thumbnail}}" alt="thumbnail">
                            </button>
                        </div>
                        <div class="col-sm-8">
                            <div class="card-body">
                                <h5 class="card-title">{{data.title}}</h5>
                                <p class="card-text">
                                    {% for author in data.authors %}
                                    {{author}}
                                    {% endfor %}
                                    著
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>

        {% endfor %}
    </div>
    <div id="more_search_button" class="text-center">
        <button type="button" class="btn btn-outline-normal searcbutton">
            <span class="material-icons big-circle">
                arrow_drop_down_circle
            </span>
            さらに検索
        </button>
    </div>
</div>

{% endblock %}
{% block scripts %}
<script>
    // djangoでajaxを使う為のの設定
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');
    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
        beforeSend: function (xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });

    // データが無い時は更に検索ボタンを隠す
    function display_more_search() {
        if ($("#searchresult form").length == 0) {
            $("#more_search_button").css("display", "none");
        }
        else if ($(".err_msg").text() != "") {
            $("#more_search_button").css("display", "none");
        }
        else {
            $("#more_search_button").show();
        }
    }


    var next_int = 0;
    display_more_search();
    $("#top_searchbutton").on("click", function () {
        next_int = 0;
        $("#searchresult").empty();
    });

    $(".searcbutton").on("click", function () {
        // ajaxでデータ取得 と next_int　の更新
        var auth = $("#author").val();
        var title = $("#title").val();
        $.ajax({
            url: "{% url 'Books:book_search' %}",
            method: "POST",
            data: {
                author: auth,
                title: title,
                next_int: next_int
            },
            timeout: 5000,
        })
            .done(function (result) {
                $(".err_msg").text("")
                var datas = result.datas;
                next_int += 1;
                for (var i in datas) {
                    var data = datas[i];
                    var authors = data.authors;
                    $("#searchresult").append(
                        $('<div/>', { 'class': 'col' }).append(
                            $('<form/>', { 'action': "{% url 'Books:detail'%}", 'method': "post" }).append(
                                '{% csrf_token %}',
                                $('<input/>', { type: 'hidden', value: data.title, name: 'title' }),
                                $('<input/>', { type: "hidden", value: JSON.stringify(data.imageLinks), name: "imageLinks" }),
                                $('<input/>', { type: "hidden", value: data.description, name: "description" }),
                                $('<input/>', { type: "hidden", value: data.authors, name: "authors" }),
                                $('<input/>', { type: "hidden", value: data.publishedDate, name: "publishedDate" }),
                                $('<input/>', { type: "hidden", value: data.pageCount, name: "pageCount" }),
                                $('<div/>', { class: 'card mb-3' }).append(
                                    $('<div/>', { class: "row g-0" }).append(
                                        $('<div/>', { class: "col-sm-4" }).append(
                                            $('<button/>', { type: "submit" }).append(
                                                $('<img/>', { src: data.imageLinks.thumbnail, alt: "thumbnail" })
                                            )
                                        ),
                                        $('<div/>', { class: "col-sm-8" }).append(
                                            $('<div/>', { class: "card-body" }).append(
                                                $('<h5/>', { class: "cart-title", text: data.title }),
                                                $('<p/>', { class: "card-text", test: authors + "著" })
                                            )
                                        )
                                    )
                                )
                            )
                        )
                    );
                }
                display_more_search();
            })
            .fail(function (data) {
                $(".err_msg").text(data.responseJSON.error);
                display_more_search();
                $('body, html').animate({ scrollTop: 0 }, 100);
                return false;
            })
    })
</script>
{% endblock %}

App/Books/templates/detail.html
{% extends 'base.html' %}
{% load static %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/Login/base.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/Books/detail.css' %}">
{% endblock %}

{% block contents %}
{% load static %}

<!-- 本のタイトルなど -->
<div class="container-fluid">
    <div class="card mb-4">
        <div class="row g-0">
            <div class="col-md-2">
                <img src="{{data.imageLinks.thumbnail}}" alt="thumbnail">
            </div>
            <div class="col-md-5">
                <div class="card-body">
                    <h3 class="card-title">{{data.title}}</h3>
                    <p class="card-text text_big">{{data.publishedDate}}出版</p>
                    <p class="card-text text_big">
                        {{data.authors}}
                        著
                    </p>
                    <form method="post" action="{% url 'Books:thoughts' %}">
                        {%csrf_token%}
                        <input type="hidden" value="{{data.title}}" name="title">
                        <input type="hidden" value="False" name="readflag">
                        <button type="submit" class="btn btn-normal">
                            <span class="material-icons">
                                star
                            </span>読みたい本に登録
                        </button>
                    </form>
                    <p>
                        <button type="btn" class="btn btn-normal" data-bs-toggle="modal"
                            data-bs-target="#not_read_modal" style="white-space: nowrap;"
                            data-title="{{data.title}}"><span class="material-icons">
                                add_comment
                            </span>感想登録</button>
                    </p>
                </div>
            </div>
            <div class="col-md-5">
                <div class="card-body">
                    <h3 class="card-title">amazonで買う</h3>
                    <p class="card-text">
                        <!-- gitに載せて良いか分からないので取りあえず空白 -->

                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- あらすじ -->
<div class="container-fluid">
    <div class="card mb-3">
        <div class="card-body">
            <h3 class="card-title">作品紹介・あらすじ</h3>
            <p class="card-text">
                {{data.description}}
            </p>
        </div>
    </div>
</div>

<!-- 著者の別の作品 -->
<div class="container">
    <h2>{{data.authors}}の他の作品</h2>
    <div class="multiple-items">
        {% for res in search_result %}
        <form action="{% url 'Books:detail'%}" method="post">
            {% csrf_token %}
            <input type="hidden" value="{{res.title}}" name="title">
            <input type="hidden" value="{{res.imageLinks}}" name="imageLinks">
            <input type="hidden" value="{{res.description}}" name="description">
            <input type="hidden" value="{{res.authors}}" name="authors">
            <input type="hidden" value="{{res.publishedDate}}" name="publishedDate">
            <input type="hidden" value="{{res.pageCount}}" name="pageCount">
            <div>
                <button type="submit">
                    <img src="{{res.imageLinks.thumbnail}}" class="d-block w-100 mx-auto" alt="thumbnail"
                        style="max-height:180px; max-width: 120px;">
                </button>
                <p class="text-center">{{res.title}}</p>
            </div>
        </form>
        {% endfor %}
    </div>
</div>
</div>

{% endblock %}
{% block modal %}
{% endblock %}
{% block scripts %}

<!-- my js files -->
<script type="text/javascript" src="{% static 'js/Login/base.js' %}"></script>
<script type="text/javascript" src="{% static 'js/Books/detail.js' %}"></script>
{% endblock %}