App/App/urls.py
from django.contrib import admin
from django.urls import include, path
from Books import views

urlpatterns = [
    path("", views.book_search, name="landing_page"),
    path('login/', include('Login.urls')),
    path('book/', include('Books.urls')),
    path('admin/', admin.site.urls),
]

App/Books/urls.py
from django.urls import path

from Books import views

app_name = "Books"
urlpatterns = [
    path('', views.book_search, name='book_search'),
    path('datail', views.detail, name='detail'),
    path('thoughts/<str:title>/<str:authors>/<path:thumbnail>', views.thoughts, name='thoughts'),
    path('thoughts/<str:title>/<str:authors>/', views.thoughts, name='thoughts'),
    path('thoughts/<str:title>', views.thoughts, name='thoughts'),
    path('thoughts/', views.thoughts, name='thoughts'),
    path('readend', views.readend, name='readend'),
    path('deletenotread', views.delete_not_read, name='delete_not_read'),
    
]

App/Login/urls.py
from django.urls import path

from Login import views

app_name="Login"
urlpatterns = [
    path('', views.index, name='index'),
    path('signup', views.signup, name='signup'),
    path('logout', views.logout_user, name="logout"),
    path('config', views.user_config, name='config'),
    path('register', views.register_attr, name='register_attr'),
    path('delete', views.delete_attr, name='delete_attr'),
    path('change_password', views.change_password, name='change_password'),
    path('publish_code', views.check_and_publish_code, name="check_and_publish_code")
   
]

App/Login/models.py
from django.db import  models
from django.contrib.auth.models import AbstractUser
from django import utils

# Create your models here.
class M_User(AbstractUser):
    """
    アカウント情報を保持するモデル
    """
    username=models.TextField(primary_key=True)
    name = models.TextField(null=False, blank=False)
    password = models.TextField(null=False, blank=False)
    email= models.EmailField(null=False, blank=True)
    insertdate = models.DateField(default=utils.timezone.now)
    updatedate = models.DateField(default=utils.timezone.now)
    deleteflag = models.BooleanField(default=False)

class T_Attr(models.Model):
    """
    アカウントの属性情報(趣向)を保存するモデル。
    pkey はid,code,srting のつもり
    code はM_Stringのcode。
    """
    index = models.AutoField(primary_key=True)
    id = models.TextField()
    code = models.PositiveIntegerField( default=0)
    string= models.TextField(default="")
    insertdate = models.DateField(default=utils.timezone.now)
    updatedate = models.DateField(default=utils.timezone.now)
    deleteflag = models.BooleanField(default=False)
    class Meta:
        constraints = [
           # 複合キーが駄目っぽいので、でユニーク制約でそれっぽくする
           models.UniqueConstraint(fields=['id', 'code', 'string'], name='unique_stock')
       ]

class M_String(models.Model):
    """
    色々な文字列をdbに保持する為のモデル。
    """
    code = models.PositiveIntegerField(primary_key=True)
    string = models.TextField()
    insertdate = models.DateField(default=utils.timezone.now)
    updatedate = models.DateField(default=utils.timezone.now)
    deleteflag = models.BooleanField(default=False)


App/Login/views.py
import inspect
from django.http.response import JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.http import  HttpResponseBadRequest
from Login.models import M_User, T_Attr
from utils.make_display_data import make_user_config_data
from utils.need_login import need_login

import secrets

# Create your views here.

class SecrectCode:
    def __init__(self):
        self.secret_code=""
secretCode = SecrectCode()

def index(request):
    if request.method=="POST":
        id = request.POST["id"]
        password = request.POST["password"]
        if M_User.objects.filter(username=id, password=password).exists():
            user = M_User.objects.get(username=id, password=password)
            login(request, user)
            return redirect('/book/', permanent=True)
        else:
            return render(request, "index.html", {"msg" :"IDかPASSWORDが間違っています"})
    else:
        return render(request, "index.html")

def logout_user(request):
    """
    ログアウトします
    """
    msg={"msg":""}
    try:
        logout(request)
        msg={}
        msg["msg"] = "ログアウトしました。"
        return render(request, "index.html", msg)
    except:
        msg = {"msg" :"ログアウトに失敗しました"}
        return render(request, "index.html", msg)
        

def change_password(request):
    """
    パスワード変更する
    """
    msg={"msg":""}
    if request.method == "POST":
        if request.POST["secret_code"] != "" and request.POST["secret_code"] == secretCode.secret_code :
            # password 変更処理
            username = request.POST["username"]
            u = M_User.objects.get(username= username)
            u.password = request.POST["password"]
            u.save()
            msg["msg"] = "パスワードを変更しました。"
            return render(request, "index.html", msg)
        else:
            msg["msg"] ="パスワード変更に失敗しました。"
            return render(request, "change_password.html", msg)
    else:
        return render(request, "change_password.html")

def check_and_publish_code(request):
    """
    Ajax でリクエストが来る想定。
    パスワード変更時、id入力 -> idがあればパスワード入力フォーム表示-> パスワード変更 という流れ。    
    """
    if request.method=="POST":
        id = request.POST["id"]
        if M_User.objects.filter(username=id).exists():
            secretCode.secret_code = secrets.token_hex(16)
            return JsonResponse({"secret":secretCode.secret_code })
        else:
            return HttpResponseBadRequest(request)
    else:
        return redirect('/book/', permanent=True)

def signup(request):
    """
    新規登録画面を返します
    """
    if request.method=="POST":
        id = request.POST["id"]
        password = request.POST["password"]
        name = request.POST["name"]
        email = request.POST["email"]
        user = M_User(username = id, password = password, email = email, name = name)
        if M_User.objects.filter(username=id).exists():
            msg="既に存在しているidです。"
            res ={"msg":msg}
            return render(request, "signup.html", res)
        else:
            user.save()
            msg={}
            msg["msg"] = "ユーザー登録しました。\nログインしてください。"
            return render(request, "index.html", msg)

    return render(request, "signup.html")

@need_login(redirect_field_name='index.html', err_msg="サインアップ、ログインが必要です")
def user_config(request):
    """
    config.htmlを表示する。
    """
    data = make_user_config_data(username=request.user)
    return render(request, "config.html", data)

# この部分はajax にする予定
def register_attr(request):
    """
    ajax 処理で使用する。お気に入りを追加して、画面に表示しなおす為に、データを返す

    Returns:
        [str]: 登録されたお気に入りの名称
    """
    if request.method == "POST":
        code = request.POST.get("code", None)
        if code is None:
            return HttpResponseBadRequest(request)
        else :
            string = request.POST.get("string", "")
            if string != "" and not T_Attr.objects.filter(id=request.user, code=code, string=string).exists():
                attr = T_Attr(id=request.user, code=code, string=string)
                try:
                    attr.save()
                    data = {"string":string}
                    return JsonResponse(data)
                except Exception as e:
                    return HttpResponseBadRequest(request)        
    return HttpResponseBadRequest(request)

def delete_attr(request):
    """
    POSTでリクエストが飛んできた時のみ、T_Attr のデータを削除します
    """
    username = request.user
    if request.method == "POST":
        code  = int(request.POST.get("code",-1))
        string = request.POST.get("string","")
        try:
            attr = T_Attr.objects.get(id=username, code=code, string=string)
            attr.delete()
            data = make_user_config_data(username)
        except Exception as e:
            print(f"{inspect.currentframe().f_back.f_code.co_filename},{inspect.currentframe().f_back.f_lineno},{e}")
            data = make_user_config_data(username)
            data["msg"] = "削除に失敗"
            return render(request, "config.html", data)
        return render(request, "config.html", data)
    else:
        data = make_user_config_data(username)
        return render(request, "config.html", data)


App/Login/templates/base.html
<!DOCTYPE html>
<html lang="ja">
{% load static %}

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>
        Book Recommender
    </title>

    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    <!-- bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- slick css -->
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css" />

    <!-- CSS Files -->
    {% block styles %}
    {% endblock %}
</head>

<body class="sidebar-collapse">
    <nav class="navbar navbar-expand-xl navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'Books:book_search'%}">
                <h2>Book Reccomend{% block page_title %}{% endblock %}</h2>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
                <ul class="navbar-nav flex-row flex-wrap me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'Books:book_search'%}">
                            <span class="material-icons">
                                search
                            </span>BookSearch
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " aria-current="page" href="{% url 'Login:signup'%}">
                            <i class="material-icons">account_circle</i>SignUp
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'Login:index'%}">
                            <i class="material-icons">login</i>Login
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'Login:logout'%}">
                            <i class="material-icons">logout</i>Logout
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'Login:config'%}">
                            <i class="material-icons">settings</i>Config
                        </a>
                    </li>
                </ul>
                <ul class="navbar-nav flex-row flex-wrap ms-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" rel="tooltip" title="" data-placement="bottom"
                            href="https://twitter.com/masamunenoheya" target="_blank"
                            data-original-title="Follow us on Twitter" rel="nofollow">
                            <i class="fa fa-twitter"></i>Twitter
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" rel="tooltip" title="" data-placement="bottom"
                            href="https://github.com/msamunetogetoge" target="_blank"
                            data-original-title="Follow us on github" rel="nofollow">
                            <i class="fa fa-github"></i>GitHub
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>


    {% block contents %}
    {% endblock %}

    {% block modals %}
    <!--既読にするmodal -->
    <div class="modal" tabindex="-1" id="not_read_modal" aria-labelledby="not_read_modal_label" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="not_read_modal_label">既読本へ登録</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form action="{% url 'Books:thoughts'%}" method="post" class="text-center">
                    {% csrf_token %}
                    <div class="modal-body">
                        <div class="card-text mb-3">
                            <label class="form-label pull-left mb-3" for="title_textbox">タイトル</label>
                            <div class="">
                                <input id="title_textbox" class="form-control" name="title" readonly>
                            </div>
                        </div>
                        <div class="card-text mb-3">
                            <label class="pull-left form-label mb-3" for="readdate_textbox">読書日</label>
                            <div class="">
                                <input type="date" id="readdate_textbox" name="readdate" required class="form-control">
                            </div>
                        </div>
                        <div class="card-text mb-3">
                            <label class="pull-left form-label mb-3" for="thoughts_textbox">感想</label>
                            <div class="">
                                <textarea id="thoughts_textbox" class="form-control thoughts_textbox" required autofocus
                                    name="thoughts" rows="4"> </textarea>
                                <div class="invalid-feedback">感想は300文字までです。</div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">キャンセル</button>
                        <button type="submit" class="btn btn-primary" id="thoughts_modal_submit_button">登録</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% endblock %}
    <footer class="container-fluid border-top bg-white fixed-bottom text-center">
        <small>
            &copy;
            <script>
                document.write(new Date().getFullYear())
            </script>, made with <i class="material-icons">favorite</i> by
            <a href="https://github.com/msamunetogetoge" target="_blank">Masamunenoheya</a>
        </small>
    </footer>
    <!-- jquery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
        integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <!-- js plugin -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"
        integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
    <!-- slick -->
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

    {% block scripts %}
    {% endblock %}
</body>

</html>

App/Login/templates/config.html
{% extends 'base.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/Login/base.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/Login/config.css' %}">
{% endblock %}

{% block contents %}
<!-- 作家表示 -->
<div class="container-fluid">
    {{msg}}
    <div class="card card-container mb-6">
        <h5 class="card-header"> <span class="material-icons">
                star
            </span>お気に入りの作家</h5>
        <div class="card-body">
            <ul class="list-group">
                <div id="auth_list">
                    {% for a in auth %}
                    <form method="post" action="{% url 'Login:delete_attr' %}">
                        {%csrf_token%}
                        <li class="list-group-item d-flex justify-content-between align-items-center ">
                            {{a}}
                            <a href="#" class="clear_button">
                                <input type="hidden" value="{{a}}" name="string">
                                <input type="hidden" value="0" name="code">
                                <span class="material-icons">clear</span>
                            </a>
                        </li>
                    </form>

                    {% endfor %}
                </div>
                <a data-bs-toggle="collapse" href="#collapseAuth" role="button" aria-expanded="false"
                    aria-controls="collapseAuth">
                    <span class="material-icons">
                        add
                    </span>
                </a>
                <div class="collapse" id="collapseAuth">
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" placeholder="作家名" aria-label="Author Name"
                            aria-describedby="auth_add" id="auth_add_text">
                        <button class="btn btn-outline-primary" type="button" id="auth_add">追加</button>
                    </div>
                </div>
            </ul>
        </div>
    </div>
</div>

<!-- 読みたい本表示 -->
<div class="container-fluid">
    <div class="card card-container mb-6">
        <h5 class="card-header"> <span class="material-icons">bookmark</span>読みたい本</h5>
        <div class="card-body">
            <ul class="list-group">
                <div id="not_read_list">
                    {% for r_data in not_readdata %}
                    <li class="list-group-item d-flex justify-content-between align-items-center ">
                        <div class="title_div">
                            {{r_data.title}}
                        </div>
                        <div>
                            <div class="row">
                                <div class="col">
                                    <button type="btn" class="btn btn-normal" data-bs-toggle="modal"
                                        data-bs-target="#not_read_modal" style="white-space: nowrap;"
                                        data-title="{{r_data.title}}">既読にする</button>
                                </div>
                                <div class="col">
                                    <form method="post" action="{% url 'Books:delete_not_read' %}">
                                        {%csrf_token%}
                                        <a href="#" class="clear_button">
                                            <input type="hidden" value="{{r_data.title}}" name="title">
                                            <span class="material-icons">clear</span>
                                        </a>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </li>

                    {% endfor %}
                </div>
            </ul>

        </div>
    </div>
</div>
<!-- 読んだ本表示 -->
<div class="container-fluid">
    <div class="card card-container mb-6">
        <h5 class="card-header"><span class="material-icons">auto_stories</span>既読本</h5>
        <div class="card-body">
            <li class="list-group-item list-group-item-info d-flex justify-content-between align-items-center ">
                <div>
                    タイトル
                </div>
                <div>
                    読書完了日
                </div>
            </li>
            {% for r_data in readdata %}
            <div>
                <li
                    class="list-group-item d-flex justify-content-between align-items-center list-group-item-action readdata">
                    <div id="title">
                        {{r_data.title}}
                    </div>
                    <div id="readdate">
                        {{r_data.readdate}}
                    </div>

                </li>
                <button type="btn" class="btn btn-normal" data-bs-toggle="modal" data-bs-target="#not_read_modal"
                    data-title="{{r_data.title}}" data-readdate="{{r_data.readdate}}"
                    data-thoughts="{{r_data.thoughts}}" id="readdata_update" style="display: none;"></button>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<!-- ジャンル表示 -->
<div class=" container-fluid" style="display: none;">
    <div class="card card-container mb-6">
        <h5 class="card-header">お気に入りのジャンル</h5>
        <div class="card-body">
            <ul class="list-group">
                {% for ge in genre %}
                <li class="list-group-item d-flex justify-content-between align-items-center">{{ge}}
                    <a href="#">
                        <span class="material-icons">clear</span>
                    </a>
                </li>
                {% endfor %}
                <a data-bs-toggle="collapse" href="#collapseGenre" role="button" aria-expanded="false"
                    aria-controls="collapseGenre">
                    <span class="material-icons">
                        add
                    </span>
                </a>
                <div class="collapse" id="collapseGenre">
                    ラジオボタンと、追加ボタンみたいにする？
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" placeholder="ジャンルはselect要素" aria-label="Genre Name"
                            aria-describedby="genre_add">
                        <button class="btn btn-outline-primary" type="button" id="genre_add">追加</button>
                    </div>
                </div>
            </ul>
        </div>
    </div>
</div>


{% endblock %}

{% block modal %}
{% endblock %}

{% block ajax %}
{% endblock %}

{% block scripts %}
<!-- my js file -->
<script type="text/javascript" src="{% static 'js/Login/config.js' %}"></script>
<script>
    // ajax使う為の設定
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');
    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
        beforeSend: function (xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });

    // お気に入り作家を登録する
    $("#auth_add").click(
        function () {
            if ($("#auth_add_text").val() != "") {
                var auth = $("#auth_add_text").val();
                $.ajax({
                    url: "{% url 'Login:register_attr' %}",
                    method: "POST",
                    data: {
                        code: "0",
                        string: auth,
                    },
                    timeout: 5000,
                })
                    .done(function (data) {
                        $("#auth_list").append('<form method="post" action=' + '{% url "Login:delete_attr" %}' + '>{%csrf_token%}<li class="list-group-item d-flex justify-content-between align-items-center ">' + auth + '<a href="#" class="clear_button"><input type="hidden" value="{{a}}" name="string"><input type="hidden" value="0" name="code"><span class="material-icons">clear</span></a></li></form>');
                    })
                    .fail(function () {
                        alert("お気に入り登録に失敗しました。同じ名前の作家は登録できません。");
                    })
                    .always(function () {
                        $("#auth_add_text").val('');
                    });
            }
        });
</script>
{% endblock %}

App/Login/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/Login/base.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/Login/index.css' %}">
{% endblock %}

{% block contents %}

<div class="container">
    <div class="card card-container mb-6">
        <h5 class="card-header">Book Recommender</h5>
        <div class="card-body">
            <form action="{% url 'Login:index'%}" method="post" class="text-center form-signin">
                {% csrf_token %}
                <p class="card-text"><input class="form-control id_textbox" placeholder="ID" required autofocus
                        name="id"></p>
                <p class="card-text"><input class="form-control password_textbox" type="password" placeholder="PASSWORD"
                        required name="password"></p>
                <p class="card-text"><a href="{% url 'Login:change_password' %}">パスワードをお忘れの場合</a></p>
                <button class="btn btn-lg btn-primary btn-block btn-signin" type="submit">Login</button>
                <p class="err_msg">{{msg|linebreaksbr}}</p>
        </div>
        </form>
    </div>
</div>

{% endblock %}

App/Login/templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/Login/base.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/Login/signup.css' %}">
{% endblock %}

{% block contents %}

<div class="container-fluid">
    <div class="card card-container mb-6">
        <h5 class="card-header">Book Recommender</h5>
        <div class="card-body">
            <form action="{% url 'Login:signup'%}" method="post" class="text-center form-signin form-group">
                {% csrf_token %}
                <div class="card-text row mb-3">
                    <label class="col-sm-3 col-form-label " for="name_textbox">名前</label>
                    <div class="col-sm-9">
                        <input id="name_textbox" class="form-control name_textbox" required autofocus name="name">
                        <div class="valid-feedback">O.K.</div>
                        <div class="invalid-feedback">名前は64文字以内です。</div>
                    </div>
                </div>
                <div class="card-text row mb-3 ">
                    <label class="col-sm-3 col-form-label" for="id_textbox">ID</label>
                    <div class="col-sm-9">
                        <input id="id_textbox" class="form-control id_textbox" required autofocus name="id">
                        <div class="valid-feedback">O.K.</div>
                        <div class="invalid-feedback">idは半角英数字16文字以内です。</div>
                    </div>
                </div>
                <div class="card-text row mb-3 email_form">
                    <label class="col-sm-3 col-form-label " for="email_textbox">Email</label>
                    <div class="col-sm-9">
                        <input id="email_textbox" class="form-control email_textbox" type="email" autofocus
                            name="email">
                        <div class="valid-feedback">O.K.</div>
                        <div class="invalid-feedback">emailは半角英数字64文字以内です。</div>
                    </div>
                </div>
                <div class="card-text row mb-3">
                    <label class="col-sm-3 col-form-label" for="pass_textbox">パスワード</label>
                    <div class="col-sm-9">
                        <input id="pass_textbox" class="form-control password_textbox" type="password" required
                            autofocus name="password">
                        <div class="valid-feedback">O.K.</div>
                        <div class="invalid-feedback">パスワードは半角英数字32桁までです。</div>
                    </div>
                </div>
                <div class="card-text row mb-3">
                    <label class="col-sm-3 col-form-label" for="pass_textbox_again">確認</label>
                    <div class="col-sm-9">
                        <input id="pass_textbox_again" class="form-control" type="password" required autofocus
                            name="password_again">
                        <div class="valid-feedback">O.K.</div>
                        <div class="invalid-feedback">入力されたパスワードが一致しません。</div>
                    </div>
                </div>
                <button class="btn btn-lg btn-primary btn-block btn-signin" type="submit" id="signup_button"
                    onclick="check_password_confirm('pass_textbox_again', 'signup_button');">登録</button>
                <div class="err_msg">
                    {{msg}}
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<!-- my js files -->
<script type="text/javascript" src="{% static 'js/Login/base.js' %}"></script>
<script type="text/javascript" src="{% static 'js/Login/signup.js' %}"></script>
{% endblock %}